#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

bspc config top_padding           18
bspc config border_width          2
bspc config window_gap            12
bspc config focus_follows_pointer true

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color   "$color1"
bspc config active_border_color   "$color2"
bspc config focused_border_color  "$color3"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
